name: Push-to-EC2

on:
 push:
  branches:
   - main

jobs:
 deploy:
  name: Deploy Python app to EC2 
  runs-on: ubuntu-latest

  steps:
   - name: Checkout the files
    uses: actions/checkout@v2
    with:
        python-version: 3.9

    # Assuming Python and dependencies are setup on the EC2 instance
   - name: Deploy to Server 1
    uses: easingthemes/ssh-deploy@main
    env:
     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
     REMOTE_HOST: ${{ secrets.HOST_DNS }}
     REMOTE_USER: ${{ secrets.USERNAME }}
     TARGET: ${{ secrets.TARGET_DIR }}
     ARGS: "rsync -r --exclude='__pycache__' . ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:${{ secrets.TARGET_DIR }}" 

   - name: Executing remote commands
    uses: appleboy/ssh-action@master
    with:
     host: ${{ secrets.HOST_DNS }}
     username: ${{ secrets.USERNAME }}
     key: ${{ secrets.EC2_SSH_KEY }}
     script: |
      cd ${{ secrets.TARGET_DIR }} 
      # Install dependencies if needed
      pip install -r requirements.txt 

      # Run the Python app (adjust as needed)
      nohup python3 app.py & 
